[package]
name = "eip-1967-proxy-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
web3 = "0.19.0"
tokio = { version = "1.29.1", features = ["full"] }
